### ISSUE TITLE
airconwithme

### ISSUE THREAD

**Issue by Stephan296** [jnimmo/pyIntesisHome#11]
Hello, What a great project.
I have a Airconwithme device, so can i also create a homeassistant component for airconwithme?
The site looks the same....

**Comment by jnimmo** [comment]
Depends, can you log into the intesishome mobile app using your airconwithme credentials?

**Comment by Stephan296** [comment]
I just tried, but thats not possible. It's from the company, can i change a web address or something?
EDIT:

I found something:

`$ipAddress = "192.168.3.217"

#Login
$response = Invoke-Restmethod -Uri "http://$ipAddress/api.cgi" -Method "POST" -Headers @{"Cookie"="Intesis-Webserver={%22sessionID%22:null}"; "Origin"="http://$ipAddress"; "Accept-Encoding"="gzip, deflate"; "Accept-Language"="en-US,en;q=0.9,nl;q=0.8"; "User-Agent"="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"; "Accept"="application/json, text/javascript, */*; q=0.01"; "Referer"="http://$ipAddress/"; "X-Requested-With"="XMLHttpRequest"; "DNT"="1"} -ContentType "application/json; charset=UTF-8" -Body "{`"command`":`"login`",`"data`":{`"username`":`"admin`",`"password`":`"admin`"}}";
$sessionId = $response.data.id.sessionID

# Set mode to Heat
Invoke-Restmethod -Uri "http://$ipAddress/api.cgi" -Method "POST" -Headers @{"Cookie"="Intesis-Webserver={%22sessionID%22:%22$sessionId%22}"; "Origin"="http://$ipAddress"; "Accept-Encoding"="gzip, deflate"; "Accept"="application/json, text/javascript, */*; q=0.01"; "Referer"="http://$ipAddress/"; "X-Requested-With"="XMLHttpRequest"; "DNT"="1"} -ContentType "application/json; charset=UTF-8" -Body "{`"command`":`"setdatapointvalue`",`"data`":{`"sessionID`":`"$sessionId`",`"uid`":2,`"value`":1}}"
# Set fan speed to speed 3
Invoke-WebRequest -Uri "http://$ipAddress/api.cgi" -Method "POST" -Headers @{"Cookie"="Intesis-Webserver={%22sessionID%22:%22$sessionId%22}"; "Origin"="http://$ipAddress"; "Accept-Encoding"="gzip, deflate"; "Accept"="application/json, text/javascript, */*; q=0.01"; "Referer"="http://$ipAddress/"; "X-Requested-With"="XMLHttpRequest"; "DNT"="1"} -ContentType "application/json; charset=UTF-8" -Body "{`"command`":`"setdatapointvalue`",`"data`":{`"sessionID`":`"$sessionId`",`"uid`":4,`"value`":3}}"
# Set temperature to 23C
Invoke-WebRequest -Uri "http://$ipAddress/api.cgi" -Method "POST" -Headers @{"Cookie"="Intesis-Webserver={%22sessionID%22:%22$sessionId%22}"; "Origin"="http://$ipAddress"; "Accept-Encoding"="gzip, deflate"; "Accept"="application/json, text/javascript, */*; q=0.01"; "Referer"="http://$ipAddress/"; "X-Requested-With"="XMLHttpRequest"; "DNT"="1"} -ContentType "application/json; charset=UTF-8" -Body "{`"command`":`"setdatapointvalue`",`"data`":{`"sessionID`":`"$sessionId`",`"uid`":9,`"value`":230}}"
# Set position to Swing
Invoke-WebRequest -Uri "http://$ipAddress/api.cgi" -Method "POST" -Headers @{"Cookie"="Intesis-Webserver={%22sessionID%22:%22$sessionId%22}"; "Origin"="http://$ipAddress"; "Accept-Encoding"="gzip, deflate"; "Accept"="application/json, text/javascript, */*; q=0.01"; "Referer"="http://$ipAddress/"; "X-Requested-With"="XMLHttpRequest"; "DNT"="1"} -ContentType "application/json; charset=UTF-8" -Body "{`"command`":`"setdatapointvalue`",`"data`":{`"sessionID`":`"$sessionId`",`"uid`":5,`"value`":10}}"
# Turn on A/C
Invoke-WebRequest -Uri "http://$ipAddress/api.cgi" -Method "POST" -Headers @{"Cookie"="Intesis-Webserver={%22sessionID%22:%22$sessionId%22}"; "Origin"="http://$ipAddress"; "Accept-Encoding"="gzip, deflate"; "Accept"="application/json, text/javascript, */*; q=0.01"; "Referer"="http://$ipAddress/"; "X-Requested-With"="XMLHttpRequest"; "DNT"="1"} -ContentType "application/json; charset=UTF-8" -Body "{`"command`":`"setdatapointvalue`",`"data`":{`"sessionID`":`"$sessionId`",`"uid`":1,`"value`":1}}"`

**Comment by grischard** [comment]
You can change the web address in the INTESIS_URL in pyintesishome.py - does that work?

**Comment by patrickvorgers** [comment]
Only changing the INTESIS_URL in pyintesishome.py does not work. I tried that but you will run into an exception. After some digging around I found out that the Airconwithme doesn't return any installations. The list is empty. I made a quick hack and got the Airconwithme unit working now. 

I changed the following lines of code:
`INTESIS_URL = "https://user.airconwithme.com/api.php/get/control"`

In the function: `def poll_status` change

```
# Update device status
for status in status_response['status']['status']:
  self._update_device_state(status['deviceId'], status['uid'], status['value'])
```

into

```
# Update device status
for status in status_response['status']['status']:
  deviceId = str(status['deviceId'])
  if deviceId not in self._devices:
    _LOGGER.info("Adding Airconwithme device ID %s", deviceId)
    self._devices[deviceId] = {"name": "Airconwithme", "widgets": {}}
    _LOGGER.debug(repr(self._devices))
  self._update_device_state(deviceId, status['uid'], status['value'])
```

It basically creates the missing device while looping through the status list.
It is probably not the best fix but at least we now know that the Airconwithme unit also works with some minor changes

**Comment by patrickvorgers** [comment]
@grischard @sytone 
So after some more testing I saw that the API version was different. By just changing the URL and the API version it now works for the Airconwithme devices. The API version is 1.6.2 in stead of 1.8.5. By specifying 1.6.2 it will return the installations in the initial call

```
#INTESIS_URL = "https://user.intesishome.com/api.php/get/control"^M
INTESIS_URL = "https://user.airconwithme.com/api.php/get/control"^M
INTESIS_CMD_STATUS = '{"status":{"hash":"x"},"config":{"hash":"x"}}'^M
#INTESIS_API_VER = "1.8.5"^M
INTESIS_API_VER = "1.6.2"^M
```

So this could be incorporated as a parameter so that the code can support both intesishome and airconwithme,

**Comment by jnimmo** [comment]
Thanks very much @PatrickV2, the library now supports Airconwithme by passing devicetype into the constructor, and I've updated the Home Assistant component to provide the option
