### ISSUE TITLE
Error while running intesishome integration (many times a day)

### ISSUE THREAD

**Issue by browetd** [jnimmo/pyIntesisHome#13]
Here are two error messages I am getting (many times a day for the first one)... Not sure if it is generated by the integration or a connection issue with the API or simply a network error...
I have 11 devices connected on two sites (one local with home assistant server, one remote). 
Nevertheless, this integration is working sucessfully ... Great job ! 
Thank you for your help.  

``2019-11-11 07:31:53 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyintesishome/pyintesishome.py", line 102, in data_received
    jsonResponse = json.loads(line)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 11 (char 10)

I have also this error but way less frequent:

`2019-11-11 04:56:35 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 813, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyintesishome/pyintesishome.py", line 102, in data_received
    jsonResponse = json.loads(line)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 12 (char 11)
`

**Comment by jnimmo** [comment]
Hey @browetd, can you try running the latest code from my PR https://github.com/home-assistant/home-assistant/pull/25364/files
(will be a good load test for it actually) - it now is using  a different method of doing the server comms which should be more async friendly, will be interesting to see if it works any better.
Cheers

**Comment by browetd** [comment]
Hello...  I downloaded the last version of the 3 files available on GitHub...
I got the following error at startup:

2019-12-01 14:52:28 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform intesishome
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/intesishome/climate.py", line 98, in async_setup_platform
    device_type=device_type,
TypeError: __init__() got an unexpected keyword argument 'websession'

Let me know if this error is related to my config (HA in venv, 0.102.2, python 3.7.3 on raspberry pi 4)
Thank you for your help...

**Comment by jnimmo** [comment]
Ah sorry forgot pip might not handle upgrades for custom components 
pip install pyintesishome —upgrade
Should bring it up to v1.1 and fix the problem

**Comment by browetd** [comment]
I will test tomorrow ... but if it is not working as expected how can I go back to the version I am currently running ?  For the climate.py, it is easy as I have a backup but for "pyintesishome", any possibility to go back to the version 0.8 (I think I am running this version for the time being).  How can I find the current version of "pyintesishome" ?  Should I add a "--version=0.8" instead of "--upgrade" in the pip instruction ?  Thank you for help and your hard work... Didier

**Comment by jnimmo** [comment]
Thanks, To downgrade it’s just a
pip uninstall pyintesishome
pip install pyintesishome==0.8

Please note I’ve bumped to v1.2 now

**Comment by browetd** [comment]
Hello...  I updated pyintesishome to 1.2... It was my mistake... the manifest json file had still the reference to 0.8... So the upgrade should have been automatic without my mistake...  Test started succesfully: intesishome up and running !

**Comment by browetd** [comment]
Here is a test I made installing pyintesishome in the virtual environment and checking the installed version...  1.2 is installed before Home Assistant starts... but during the start of HA, the 1.2 is replaced by 0.8...

``
... Stopping Home Assistant

(homeassistant) homeassistant@browetpierre:~/.homeassistant $ pip install pyintesishome
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyintesishome in /srv/homeassistant/lib/python3.7/site-packages (0.8)
(homeassistant) homeassistant@browetpierre:~/.homeassistant $ pip uninstall pyintesishome
Uninstalling pyintesishome-0.8:
  Would remove:
    /srv/homeassistant/lib/python3.7/site-packages/pyintesishome-0.8.dist-info/*
    /srv/homeassistant/lib/python3.7/site-packages/pyintesishome/*
Proceed (y/n)? y
  Successfully uninstalled pyintesishome-0.8
(homeassistant) homeassistant@browetpierre:~/.homeassistant $ pip install pyintesishome
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyintesishome
  Using cached https://files.pythonhosted.org/packages/91/29/cc05c55519cb584476bac7701b603967854f966fe0044a2fd8c40c4a0cb0/pyintesishome-1.2-py3-none-any.whl
Installing collected packages: pyintesishome
Successfully installed pyintesishome-1.2

... Starting Home Assistant 

(homeassistant) homeassistant@browetpierre:~/.homeassistant $ pip install pyintesishome
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pyintesishome in /srv/homeassistant/lib/python3.7/site-packages (0.8)
(homeassistant) homeassistant@browetpierre:~/.homeassistant $

**Comment by grischard** [comment]
Fantastic, thanks for the feedback @browetd!

**Comment by browetd** [comment]
Sofar the new version (pyintesishome 1.2) is running smoothly for 4 days (no error at all)...  Great job !!!  Thank you for your work.
