### ISSUE TITLE
Integrate into HACS (Home Assistant Community Store)?

### ISSUE THREAD

**Issue by mitchins** [jnimmo/pyIntesisHome#17]
More of a possible todo, than an issue.
This is a fantastic plugin @jnimmo and I know there's been issues the HASS team has had with the code being imported into HASS itself, but truth be told it works just fine and I love it.

It'd be great to manage it via HACS which would provide almost the same benefit without the restrictions.
I'm raising this issue to create awareness, and yes volunteering to put my hand up, but I wanted to get a consensus/assent.

Documentation is [here](https://hacs.xyz/docs/publish/start)

At a minimum we'd need:
 * hacs.json
 * Releases with tags.

Thanks again for the great library, I'm happy to try this out, but only if the direction is endorsed by the maintainer :)

**Comment by grischard** [comment]
Hi @mitchins, I hope you'll be very happy to see your issue getting closed with no action ;)

https://www.home-assistant.io/integrations/intesishome/

**Comment by mitchins** [comment]
You’re awesome, thanks!

**Comment by grischard** [comment]
Tell @jnimmo he's awesome, not me :)
