### ISSUE TITLE
config_fan_map is an int?

### ISSUE THREAD

**Issue by issacg** [jnimmo/pyIntesisHome#20]
I'm running into a situation where several devices return a map object for `_devices[deviceId].config_fan_map` are giving me an integer value rather than an object value, and thus raising an exception when calling `get_fan_speed_list`

I get the following values for `config_fan_map` for the six devices in my intesis account:

- `{0: 'auto', 1: 'low', 2: 'medium', 3: 'high'}`
- `32783`
- `{1: 'low', 2: 'medium', 3: 'high'}`
- `{1: 'quiet', 2: 'low', 3: 'medium', 4: 'high'}`
- `7`
- `{1: 'quiet', 2: 'low', 3: 'medium', 4: 'high'}`

**Comment by jnimmo** [comment]
I think this should be resolved in the update I've just been working on.
What fan speeds does the device with 7 have - auto, low and high?
Cheers

**Comment by issacg** [comment]
Auto, high, medium, low, quiet

**Comment by issacg** [comment]
Actually just realized something. The unit supports what I sent above, but intesis has 2 modes and auto. 

Very possibly high, low and auto like you suggested

**Comment by jnimmo** [comment]
If you'd like to test the update, you can drop these https://github.com/jnimmo/home-assistant/tree/dev/homeassistant/components/intesishome files into custom_components/intesishome
then run a 'pip3 update pyintesishome' to update to 1.7.1
Once that's updated you can run Home Assistant with hass --skip-pip so it doesn't downgrade pyIntesisHome

**Comment by issacg** [comment]
Looking good for the `7` device (I removed the `32783` device from  my intesis account so it wasn't tested).  Note that this is a homeassistant instance that I help to manage for someone else, so I'll need to get feedback that it's working completely as expected only after the release (mucking with components would be a PITA there)

Also, FYI, it's enough (and IMHO easier) to just bump the library version in `manifest.json` in the component than running `pip` on my own (and also will work with a Hass.io setup, where running with --skip-pip is AFAIK non-trivial)
