### ISSUE TITLE
clarification on "operating mode"

### ISSUE THREAD

**Issue by ericbogs** [jnimmo/pyIntesisHome#24]
Really appreciate this script -- thanks for your efforts.

When I set `mode` to auto (rather than heat/cool), is there a way to detect if the Intesis unit ends up supplying heat or cooling?

I was hoping `operating_mode` might provide that. 

E.g. `mode` is "auto", and then `operating_mode` might be "heating" or "cooling" based on temperature.

Any possibility to get this state?

**Comment by James712346** [comment]
On line 734 there is a function under the Intesishome class that get and return the operating_mode state, so I would give that a try
```py
def get_mode(self, deviceId) -> str:
     """Public method returns the current mode of operation."""
     if "mode" in self._devices[str(deviceId)]:
         return self._devices[str(deviceId)]["mode"]
     elif "operating_mode" in self._devices[str(deviceId)]:
         return self._devices[str(deviceId)]["operating_mode"]
```
It should be just `YourIntesishomeObject.get_mode(deviceId)`

**Comment by James712346** [comment]
I don't think thats possible, as I think the auto function is handled by the aircon unit, Intesishome just sends the commands through IR transmitter, just like your aircon remote. So when you set the mode to auto, it sends the IR command to the aircon unit and its the your aircon's job to workout if it should cool or heat not Intesishome. But I could be wrong
I would strongly advice you to not use auto, as I've always found it extremely inaccurate, instead make your script decide if it should heat or cool or even dry if current temp is close to target temp by 1-3 degrees
