### ISSUE TITLE
[Home Assistant] Try to reconnect every x minutes/seconds (or poll then reconnect) 

### ISSUE THREAD

**Issue by James712346** [jnimmo/pyIntesisHome#25]
I'm getting a little annoyed as my home network keeps disconnecting from the internet (AU internet for you), but due to this, I need to restart my home assistant insentance and I was hoping you could add feature that trys to reconnect every x minutes/seconds (or poll then reconnect) and have a configable element in Home Assistant like retry_connect_every: 1 
Also if there already a feature like this, the debug logs just shows nothing and when I try to send a command to intesishome, the debug logs just show `2020-12-10 21:32:40 DEBUG (MainThread) [homeassistant.components.intesishome.climate] Setting IntesisHome to cool mode` and is unresponsive

**Comment by grischard** [comment]
I wonder if the official app has some kind of keepalive. Does it suffer from the same problem?

**Comment by jnimmo** [comment]
We just need to implement a better reconnect pattern, at the moment it's very untidy. I'm thinking of making it poll (https) unless a command is issued, then we connect and stay connected until the connection dies, then go back to polling.
The mobile app of course is not designed to maintain a persistent connection 24x7

**Comment by jnimmo** [comment]
Hopefully this has been resolved already - but further enhancements have been made in 1.8.1 which will be included in an upcoming release of HA
