### ISSUE TITLE
PyPI version does not match Github release - 1.7.7

### ISSUE THREAD

**Issue by Neonkoala** [jnimmo/pyIntesisHome#32]
The files available here for 1.7.7 - https://pypi.org/project/pyintesishome/1.7.7/#files do not match the Github release of 1.7.7.

This means I can't use the Anywair functionality that was added. Can you please reupload to PyPI?

**Comment by jnimmo** [comment]
Sorry for the delayed response - can you use 1.8.0? If not I'll look into resolving it

**Comment by Neonkoala** [comment]
No worries, yep 1.8.0 should work fine thanks.
