### ISSUE TITLE
Set Value not implemented

### ISSUE THREAD

**Issue by MateRadz** [jnimmo/pyIntesisHome#42]
async def _set_value(self, device_id, uid, value):
        """Internal method to send a value to the device."""
        raise NotImplementedError()

Arę there any plans to do it?

**Comment by jnimmo** [comment]
What are you trying to achieve? This is just an internal helper method so if it's not implemented for one platform it may not be required

**Comment by MateRadz** [comment]
What I am trying to achieve is being able to set values for the Panasonic Aquarea heatpump including ON/OFF state for the pump. Any help appreciated.
