### ISSUE TITLE
pyIntesisHome lost connection to the IntesisHome server

### ISSUE THREAD

**Issue by jnimmo** [jnimmo/pyIntesisHome#45]
Im with latest versión of core and supervisor in HA. No update status, and climate entity is marked as unavailable. i cant use the climate from HA.

With AC Cloud APP works without problems. Tried to reconnect Intesishome unit, reboot router, restart HA several times....

Logger: pyintesishome
Source: runner.py:119
First occurred: 17:34:08 (1 occurrences)
Last logged: 17:34:08

pyIntesisHome lost connection to the IntesisHome server. Exception: 0 bytes read on a total of undefined expected bytes

__Originally posted by @ldsmovil in https://github.com/jnimmo/pyIntesisHome/issues/44#issuecomment-1226102023__

**Comment by ldsmovil** [comment]
Fixed with latest Ha core version, no connections drops now, finger crossed

**Comment by jnimmo** [comment]
Thanks for the update! Feel free to reopen if it continues
