### ISSUE TITLE
Component not found: IntesisHome

### ISSUE THREAD

**Issue by pcordonet** [jnimmo/pyIntesisHome#8]
Hi, 
I install this component at custom_components.

When check configuration.yaml, i have this error: Component not found: IntesisHome

Can you tell me how to install fine?

Peter
Thanks

**Comment by jnimmo** [comment]
Hi Peter, 
So you have a folder called intesishome inside custom_components? You might need to put __init__.py in there too for it to detect it perhaps.
I've just pushed an update to intesishome.py also.

**Comment by pcordonet** [comment]
Hi jnimmo,

I downloaded and copied  files to custom_components.
But i have same error.

Perhaps, is not error of this component, i have other component and don't load too.

Any ideas?

Thank you for your time.
Peter.

**Comment by jnimmo** [comment]
Hi Peter, 
You'll need three files in the following location:
custom_components/intesishome/__init__.py
custom_components/intesishome/manifest.json
custom_components/intesishome/climate.py
