### ISSUE TITLE
Advances in the intesisbox branch

### ISSUE THREAD

**Issue by ismaelrivas** [jnimmo/pyIntesisHome#9]
I am interested in knowing the advances that you have been able to do with intesisbox, I currently use tasker on my android device to manage my intesisbox.

Thanks

**Comment by jnimmo** [comment]
Hi there, I'll try and do some work on it this week

**Comment by jnimmo** [comment]
Please see https://github.com/jnimmo/hass-intesisbox for an initial release.. not sure if it will work or not!

**Comment by ismaelrivas** [comment]
Thanks. I saw the code, good job. I think I will not be able to try it
until tomorrow. I will feedback later.
